### ISSUE TITLE
ERROR: No matching distribution found for whisper (unavailable)

### ISSUE THREAD

**Issue by lnzhaotian** [mli/autocut#76]
安装时出现以下错误，不论是直接用pip安装还是用docker
`ERROR: Could not find a version that satisfies the requirement whisper (unavailable) (from autocut) (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10)`
`ERROR: No matching distribution found for whisper (unavailable)`

**Comment by ZhiyaoWen999** [comment]
Hello, 

The problem is whisper does not have py package, so we use the git method to download it.

Now they release whisper package, so we have to change the download method.

You can directly clone the repo, and change `"whisper @ git+https://github.com/openai/whisper.git"` to `"openai-whisper"` in the setup.py. Then, cd to autocut and `pip install .`

**Comment by lnzhaotian** [comment]
> Hello,
> 
> The problem is whisper did not have py package, so we use the git method to download it.
> 
> Now they release whisper package, so we have to change the download method.
> 
> You can directly clone the repo, and change `"whisper @ git+https://github.com/openai/whisper.git"` to `"openai-whisper"` in the setup.py. Then, cd to autocut and `pip install .`

Thank you very much, that solved it.

**Comment by dracula-cn** [comment]
遇到同样问题，没看明白，求教
